### ISSUE TITLE
npm run build crashes with error

### ISSUE THREAD

**Issue by Wakko90** [puikinsh/Adminator-admin-dashboard#103]
Hi there, I'm building an app using Adminator. I installed vue-loader to process .vue files and html-loader to modularize html.

# Current behavior
When running npm run dev everything is fine but when using npm run build it crashes with npm ERR! code ELIFECYCLE

If I check the build folder i see some files in there.

Here the logs i get in the terminal

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@5.8.0
3 info using node@v8.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle adminator@1.0.0~prebuild: adminator@1.0.0
6 info lifecycle adminator@1.0.0~build: adminator@1.0.0
7 verbose lifecycle adminator@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle adminator@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle adminator@1.0.0~build: CWD: /Users/alessio/Documents/repository/metromappa-backend-repo
10 silly lifecycle adminator@1.0.0~build: Args: [ '-c',
10 silly lifecycle   'npm run clean && cross-env NODE_ENV="production" webpack' ]
11 silly lifecycle adminator@1.0.0~build: Returned: code: 2  signal: null
12 info lifecycle adminator@1.0.0~build: Failed to exec build script
13 verbose stack Error: adminator@1.0.0 build: `npm run clean && cross-env NODE_ENV="production" webpack`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid adminator@1.0.0
15 verbose cwd /Users/alessio/Documents/repository/metromappa-backend-repo
16 verbose Darwin 17.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v8.11.1
19 verbose npm  v5.8.0
20 error code ELIFECYCLE
21 error errno 2
22 error adminator@1.0.0 build: `npm run clean && cross-env NODE_ENV="production" webpack`
22 error Exit status 2
23 error Failed at the adminator@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

```
 adminator@1.0.0 build /Users/alessio/Documents/repository/metromappa-backend-repo
 npm run clean && cross-env NODE_ENV="production" webpack


 adminator@1.0.0 clean /Users/alessio/Documents/repository/metromappa-backend-repo
 shx rm -rf ./build

DEPRECATION WARNING on line 1, column 8 of /Users/alessio/Documents/repository/metromappa-backend-repo/src/assets/styles/vendor/index.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

DEPRECATION WARNING on line 2, column 8 of /Users/alessio/Documents/repository/metromappa-backend-repo/src/assets/styles/vendor/index.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

DEPRECATION WARNING on line 3, column 8 of /Users/alessio/Documents/repository/metromappa-backend-repo/src/assets/styles/vendor/index.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

Hash: 34c862042c31eb48bd1a
Version: webpack 3.12.0
Time: 22265ms
                                                          Asset       Size  Chunks                    Chunk Names
                                           linea-arancione.html    2.98 kB          [emitted]
                           2c454669bdf3aebf32a1bd8ac1e0d2d6.eot    78.7 kB          [emitted]
                           e23a7dcaefbde4e74e263247aa42ecd7.ttf    78.6 kB          [emitted]
                           9c8e96ecc7fa01e6ebcd196495ed2db5.svg     222 kB          [emitted]
                    assets/6d16f95495605c95172bc8c924720bff.svg   82 bytes          [emitted]
                           674f50d287a8c48dc19ba404d20fe713.eot     166 kB          [emitted]
                         af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]
                          fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]
                           b06871f281fee6b241d60582ae9369b9.ttf     166 kB          [emitted]
                           912ec66d7572ff821749319396470bde.svg     388 kB          [emitted]  [big]
                    assets/36d50c1381fda7c71d12b6643cbe1ee0.svg   82 bytes          [emitted]
                                                      bundle.js    1.04 MB       0  [emitted]  [big]  main
                                                      vendor.js     839 kB       1  [emitted]  [big]  vendor
                                                       404.html  824 bytes          [emitted]
                                                       500.html  826 bytes          [emitted]
                                                     index.html    26.1 kB          [emitted]
                                                     blank.html    11.2 kB          [emitted]
                                                   buttons.html    10.5 kB          [emitted]
                                                  calendar.html    15.7 kB          [emitted]
                                                    charts.html      14 kB          [emitted]
                                                      chat.html    16.9 kB          [emitted]
                                                   compose.html    14.2 kB          [emitted]
                                                 datatable.html    18.6 kB          [emitted]
                                                     email.html      26 kB          [emitted]
                                                     forms.html    18.5 kB          [emitted]
                                                     linea.html    2.98 kB          [emitted]
                                               linea-verde.html    2.98 kB          [emitted]
                                              linea-gialla.html    2.98 kB          [emitted]
                          a1ecc3b826d01251edddf29c3e4e1e97.woff    56.1 kB          [emitted]
                                               linea-viola.html    2.98 kB          [emitted]
                                               google-maps.html    11.4 kB          [emitted]
                                                    signin.html     2.5 kB          [emitted]
                                                    signup.html    2.46 kB          [emitted]
                                                        ui.html      20 kB          [emitted]
                                               vector-maps.html    11.4 kB          [emitted]
                                               basic-table.html    15.1 kB          [emitted]
  assets/static/fonts/icons/fontawesome/fontawesome-webfont.eot     166 kB          [emitted]
  assets/static/fonts/icons/fontawesome/fontawesome-webfont.svg     444 kB          [emitted]  [big]
  assets/static/fonts/icons/fontawesome/fontawesome-webfont.ttf     166 kB          [emitted]
 assets/static/fonts/icons/fontawesome/fontawesome-webfont.woff      98 kB          [emitted]
assets/static/fonts/icons/fontawesome/fontawesome-webfont.woff2    77.2 kB          [emitted]
                  assets/static/fonts/icons/themify/themify.eot    78.7 kB          [emitted]
                  assets/static/fonts/icons/themify/themify.svg     234 kB          [emitted]
                  assets/static/fonts/icons/themify/themify.ttf    78.6 kB          [emitted]
                 assets/static/fonts/icons/themify/themify.woff    56.1 kB          [emitted]
          assets/static/fonts/icons/fontawesome/FontAwesome.otf     135 kB          [emitted]
                                   assets/static/images/404.png    4.62 kB          [emitted]
                                   assets/static/images/500.png     175 kB          [emitted]
          assets/static/images/datatables/sort_asc_disabled.png  148 bytes          [emitted]
                   assets/static/images/datatables/sort_asc.png  160 bytes          [emitted]
                  assets/static/images/datatables/sort_both.png  201 bytes          [emitted]
         assets/static/images/datatables/sort_desc_disabled.png  146 bytes          [emitted]
                                    assets/static/images/bg.jpg     504 kB          [emitted]  [big]
                                  assets/static/images/logo.svg    1.38 kB          [emitted]
                  assets/static/images/datatables/sort_desc.png  158 bytes          [emitted]
                                  assets/static/images/logo.png    17.8 kB          [emitted]
                                     assets/static/modello.json      77 kB          [emitted]
 [141] multi ../assets/scripts/index.js 28 bytes {0} [built]
 [142] ../assets/scripts/index.js 360 bytes {0} [built]
 [143] ../assets/styles/index.scss 1.42 kB {0} [built]
 [160] ../assets/scripts/masonry/index.js 343 bytes {0} [built]
 [225] ../assets/scripts/search/index.js 233 bytes {0} [built]
 [226] ../assets/scripts/sidebar/index.js 1.56 kB {0} [built]
 [227] ../assets/scripts/skycons/index.js 559 bytes {0} [built]
 [229] ../assets/scripts/vectorMaps/index.js 2.62 kB {0} [built]
 [230] ../assets/scripts/chat/index.js 186 bytes {0} [built]
 [231] ../assets/scripts/datatable/index.js 117 bytes {0} [built]
 [233] ../assets/scripts/datepicker/index.js 277 bytes {0} [built]
 [234] ../assets/scripts/email/index.js 325 bytes {0} [built]
 [235] ../assets/scripts/fullcalendar/index.js 1.63 kB {0} [built]
 [236] ../assets/scripts/googleMaps/index.js 1.86 kB {0} [built]
 [238] ../assets/scripts/utils/index.js 1.2 kB {0} [built]
    + 224 hidden modules

ERROR in bundle.js from UglifyJs
Unexpected token: punc ()) [bundle.js:471,35]
Child html-webpack-plugin for "404.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../404.html 1.25 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
Child html-webpack-plugin for "500.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../500.html 1.25 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
Child html-webpack-plugin for "index.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../index.html 53.1 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
Child html-webpack-plugin for "blank.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../blank.html 21.9 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
Child html-webpack-plugin for "buttons.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../buttons.html 20.7 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
Child html-webpack-plugin for "calendar.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../calendar.html 31.3 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
Child html-webpack-plugin for "charts.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../charts.html 27.4 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
Child html-webpack-plugin for "chat.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../chat.html 33.6 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
Child html-webpack-plugin for "compose.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../compose.html 28.2 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
Child html-webpack-plugin for "datatable.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../datatable.html 43.6 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
Child html-webpack-plugin for "email.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../email.html 50.6 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
Child html-webpack-plugin for "forms.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../forms.html 35.5 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
Child html-webpack-plugin for "linea.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../linea.html 3.39 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 2 hidden modules
Child html-webpack-plugin for "linea-verde.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../linea-verde.html 3.39 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 2 hidden modules
Child html-webpack-plugin for "linea-gialla.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../linea-gialla.html 3.39 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 2 hidden modules
Child html-webpack-plugin for "linea-arancione.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../linea-arancione.html 3.4 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 2 hidden modules
Child html-webpack-plugin for "linea-viola.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../linea-viola.html 3.39 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 2 hidden modules
Child html-webpack-plugin for "google-maps.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../google-maps.html 22.3 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
Child html-webpack-plugin for "signin.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../signin.html 3.83 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
Child html-webpack-plugin for "signup.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../signup.html 3.69 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
Child html-webpack-plugin for "ui.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../ui.html 36.7 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
Child html-webpack-plugin for "vector-maps.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../vector-maps.html 22.3 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
Child html-webpack-plugin for "basic-table.html":
     1 asset
       [0] /Users/alessio/Documents/repository/metromappa-backend-repo/node_modules/html-webpack-plugin/lib/loader.js!../basic-table.html 30.7 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! adminator@1.0.0 build: `npm run clean && cross-env NODE_ENV="production" webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the adminator@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alessio/.npm/_logs/2018-07-09T13_44_50_772Z-debug.log
```

# Expected behavior 
build with no errors in the terminal

# Environment
Platform: macOS high sierra

For building issues:
Node: v8.11.1          
NPM: 5.8.0

**Comment by Wakko90** [comment]
Looks like I was missing the babelrc file. Put it in place and now it's working :)

**Comment by krzysiekpiasecki** [comment]
@Wakko90 Great! So close this ticket. It's resolved.

**Comment by Wakko90** [comment]
Ok, I'd like to point out that I had a similar issue running build on netlify. This time the problem was the uglify plugin so I had to remove it in order to make it work.
