### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by prakhar-goel** [puikinsh/Adminator-admin-dashboard#114]
<h1>Bug report</h1>

# Current behavior

After I clone the repo and do `npm install` and later try to start the server by `npm run dev` or `npm start`, I get the error:
```
events.js:167
      throw er; // Unhandled 'error' event
      ^
```
The complete stack trace is:
```
$ npm start

> adminator@1.0.0 start /Users/mike/Development/personal/Adminator-admin-dashboard
> webpack-dev-server

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:3000
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at doListen (net.js:1491:7)
    at process._tickCallback (internal/process/next_tick.js:174:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1357:8)
    at process._tickCallback (internal/process/next_tick.js:174:19)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adminator@1.0.0 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adminator@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mike/.npm/_logs/2018-08-21T18_50_04_206Z-debug.log
```
# Expected behavior 

The server should have started and I should have been able to view the the admin panel at localhost:3000
## Steps to reproduce
- `git clone https://github.com/puikinsh/Adminator-admin-dashboard.git adminator`
- `cd adminator`
- `npm install`
- `npm run dev`

# Environment
Platform: 
using command `system_profiler SPSoftwareDataType` on my macbook
```
Software:

    System Software Overview:

      System Version: macOS 10.13.4 (17E199)
      Kernel Version: Darwin 17.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: mike’s MacBook
      User Name: mike
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 30 days 9 minutes
```
Browser: `Chrome Version 67.0.3396.99 (Official Build) (64-bit)`

Node and NPM versions:
Node:  `v10.0.0`         
NPM:   `6.2.0`

**Comment by krzysiekpiasecki** [comment]
@prakhar-goel Thank you for your report. It looks like a compatibility problem between **node** and **npm**.
My versions are: `Node@10.0.0` and `NPM@5.6.0`. Everything works fine. Try to downgrade your npm version.

Did you consider using nvm manager? https://github.com/creationix/nvm?

**Comment by krzysiekpiasecki** [comment]
@prakhar-goel  Closed due to inactivity.
