### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by 0xbogeyman** [puikinsh/Adminator-admin-dashboard#173]
Require stack:
- /Users/*/adminator/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /Users/*/adminator/node_modules/webpack/bin/webpack.js:143:5
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/*/adminator/node_modules/webpack/bin/webpack.js' ]
}

**Comment by krzysiekpiasecki** [comment]
Closed due inactivity and no context and additional information provided.
