### ISSUE TITLE
Webpack compilation issue

### ISSUE THREAD

**Issue by Devashan** [puikinsh/Adminator-admin-dashboard#274]
<h1>Bug report</h1>

# Current behavior
Displays the following error when running **npm start**> 

adminator@2.0.0 start A:\Programming\NodeJS\adminator
> webpack server

A:\Programming\NodeJS\adminator\node_modules\webpack-cli\bin\cli.js:1
h

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at runCli (A:\Programming\NodeJS\adminator\node_modules\webpack\bin\webpack.js:69:2)
    at Object.<anonymous> (A:\Programming\NodeJS\adminator\node_modules\webpack\bin\webpack.js:162:2)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adminator@2.0.0 start: `webpack server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adminator@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

# Expected behaviour 

Webpack compilation fails when trying to run the server.
# Environment
Platform: Windows
Browser: N/A

For building issues:
Node:  v12.18.3       
NPM:  6.14.6

Sorry, I can't help much. I'm not that well versed in webpack.

**Comment by jepperaskdk** [comment]
Can you confirm if this is still an issue? Can you try removing node_modules, running `npm install` and rerunning your command?

**Comment by jepperaskdk** [comment]
Closing as stale - please reopen if the issue persists. :)
