### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Yustyar** [puikinsh/Adminator-admin-dashboard#59]
why look like this? does not match the original, can it help me to fix this

![error1](https://user-images.githubusercontent.com/36684336/36463369-0a1c19e6-16fc-11e8-85af-875703e9523f.PNG)

**Comment by krzysiekpiasecki** [comment]
You've probably open a html file from ```src``` directory.

To build or run this app follow the [README](https://github.com/puikinsh/Adminator-admin-dashboard/blob/master/README.md) file.


```
> git clone https://github.com/puikinsh/Adminator-admin-dashboard.git adminator
> cd adminator
> npm install
> npm run dev
```

You can also call ```npm run build``` instead of  ```npm run dev``` and then manually open a file ```build/index.html```.

Don't forget close the ticket, if you have no more questions. Thanks.

**Comment by Yustyar** [comment]
please provide step by step to fix this :)

**Comment by krzysiekpiasecki** [comment]
There is no need to fix it. Just follow the instructions from [README](https://github.com/puikinsh/Adminator-admin-dashboard/blob/master/README.md) file. See section "Installing & Local Development". More questions?

**Comment by ritchie46** [comment]
Hi, Cool admin page! I've got the same errors with the css. Which version of nodejs and npm is required?

Here is my error log when running npm run build

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@5.6.0
3 info using node@v9.5.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle adminator@1.0.0~prebuild: adminator@1.0.0
6 info lifecycle adminator@1.0.0~build: adminator@1.0.0
7 verbose lifecycle adminator@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle adminator@1.0.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ritchie46/code/proSoil/app/project/templates/theme/adminator/node_modules/.bin:/home/ritchie46/opt/nodejs/bin:/home/ritchie46/scripts/path:/opt/miniconda3/bin:/home/ritchie46/bin:/home/ritchie46/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle adminator@1.0.0~build: CWD: /home/ritchie46/code/proSoil/app/project/templates/theme/adminator
10 silly lifecycle adminator@1.0.0~build: Args: [ '-c',
10 silly lifecycle   'npm run clean && cross-env NODE_ENV="production" webpack' ]
11 silly lifecycle adminator@1.0.0~build: Returned: code: 2  signal: null
12 info lifecycle adminator@1.0.0~build: Failed to exec build script
13 verbose stack Error: adminator@1.0.0 build: `npm run clean && cross-env NODE_ENV="production" webpack`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid adminator@1.0.0
15 verbose cwd /home/ritchie46/code/proSoil/app/project/templates/theme/adminator
16 verbose Linux 4.13.0-32-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v9.5.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error adminator@1.0.0 build: `npm run clean && cross-env NODE_ENV="production" webpack`
22 error Exit status 2
23 error Failed at the adminator@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

```

**Comment by ghost** [comment]
I can say that it sometimes happen, then I need to relaunch nom run dev and all works fine then

**Comment by AndreiCN** [comment]
@Yustyar please close the ticket if you have no further questions.

**Comment by krzysiekpiasecki** [comment]
@AndreiCN I think You can safely close this ticket, because of inactivity and duplication.
